[package]
name = "maid-codec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maid-utils = { path = "../maid-utils" }
static_assertions = { workspace = true }
