[package]
name = "maidness"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["no-std"]
no-std = []

[dependencies]
integral-enum = "1.2.1"
snafu = { version = "0.7.4", default-features = false }
static_assertions = "1.1.0"
